### ISSUE TITLE
Explore ability to show Signalen map for end-users or support WFS / WMS service

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#79]

**Comment by erikveerm** [comment]
Requirements of a map with open signals for end-users (reporters):
- URL of the map accessible to everyone
- Map with all open signals
- High refresh rate (virtually live data)
- Signals can be shown clustered in accordance with the current map in the back office
- No personal data is shown on the map
- In a signal the following data is shown:
     - Unique signal number
     - Date of receipt signal
     - Main category
     - Subcategory
     - Status

**Comment by CBuiVNG** [comment]
We cannot re-use the geography endpoint that is included within SIA (and currently used for maps).
- It enforces access rights (only show signals that are relevant to the user)
- it currently lacks a couple of required fields.

We cannot change the way this endpoint works, since location and category are privacy sensitive data.
We should therefore create a separate endpoint behind a feature flag
